# Generated by Django 4.0.5 on 2023-07-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={},
        ),
    ]
